import sys
from pathlib import Path

sys.path.append(str(Path(__file__).resolve().parent.parent))

from utils import (
    print_line,
    get_current_date,
    get_current_time,
    get_timestamp,
    create_reports_directory,
    save_text_file
)

print_line()

print("Current Date :", get_current_date())
print("Current Time :", get_current_time())
print("Timestamp    :", get_timestamp())

directory = create_reports_directory()

print("\nReports Directory:", directory)

filename = f"test_{get_timestamp()}.txt"

saved = save_text_file(
    filename,
    "This is a test report generated by EZENOX."
)

print("Saved File:", saved)

print_line()
